DROP TABLE IF EXISTS `#__wbadvert_advert`;
DROP TABLE IF EXISTS `#__wbadvert_campaign`;
DROP TABLE IF EXISTS `#__wbadvert_client`;
DROP TABLE IF EXISTS `#__wbadvert_group`;
DROP TABLE IF EXISTS `#__wbadvert_idx_category`;
DROP TABLE IF EXISTS `#__wbadvert_idx_client`;
DROP TABLE IF EXISTS `#__wbadvert_idx_content`;
DROP TABLE IF EXISTS `#__wbadvert_idx_group`;
DROP TABLE IF EXISTS `#__wbadvert_idx_menu`;
